In [2]:
import pickle5 as pickle
import json
from tqdm import tqdm


In [7]:
train_path = '/home/minju/path_generator/commonsense-qa/data/csqa/train.jsonl'
train_list = []

with open(train_path, 'r') as train_file:
    for line in tqdm(train_file):
        json_line = json.loads(line)
        train_list.append(json_line)

9741it [00:00, 46614.86it/s]


In [8]:
train_list[0]

{'answerKey': 'A',
 'id': '075e483d21c29a511267ef62bedc0461',
 'question': {'question_concept': 'punishing',
  'choices': [{'label': 'A', 'text': 'ignore'},
   {'label': 'B', 'text': 'enforce'},
   {'label': 'C', 'text': 'authoritarian'},
   {'label': 'D', 'text': 'yell at'},
   {'label': 'E', 'text': 'avoid'}],
  'stem': 'The sanctions against the school were a punishing blow, and they seemed to what the efforts the school had made to change?'}}

In [4]:
statement_path = '/home/minju/path_generator/commonsense-qa/data/small_csqa/statement/train.statement.jsonl'
statement_list = []

with open(statement_path, 'r') as statement:
    for line in tqdm(statement):
        json_line = json.loads(line)
        statement_list.append(json_line)

9741it [00:00, 51990.01it/s]


In [5]:
statement_list[0]

{'answerKey': 'A',
 'id': '075e483d21c29a511267ef62bedc0461',
 'question': {'question_concept': 'punishing',
  'choices': [{'label': 'A', 'text': 'ignore'},
   {'label': 'B', 'text': 'enforce'},
   {'label': 'C', 'text': 'authoritarian'},
   {'label': 'D', 'text': 'yell at'},
   {'label': 'E', 'text': 'avoid'}],
  'stem': 'The sanctions against the school were a punishing blow, and they seemed to what the efforts the school had made to change?'},
 'statements': [{'label': True,
   'statement': 'The sanctions against the school were a punishing blow, and they seemed to ignore the efforts the school had made to change.'},
  {'label': False,
   'statement': 'The sanctions against the school were a punishing blow, and they seemed to enforce the efforts the school had made to change.'},
  {'label': False,
   'statement': 'The sanctions against the school were a punishing blow, and they seemed to authoritarian the efforts the school had made to change.'},
  {'label': False,
   'statement': '

In [9]:
grounded_path = '/home/minju/path_generator/commonsense-qa/data/csqa/grounded/train.grounded.jsonl'
grounded_list = []

with open(grounded_path, 'r') as grounded:
    for line in tqdm(grounded):
        json_line = json.loads(line)
        grounded_list.append(json_line)

48705it [00:00, 101001.03it/s]


In [10]:
grounded_list[0]

{'sent': 'The sanctions against the school were a punishing blow, and they seemed to ignore the efforts the school had made to change.',
 'ans': 'ignore',
 'qc': ['blow',
  'change',
  'effort',
  'efforts',
  'sanction',
  'sanctions',
  'school',
  'seem',
  'seemed'],
 'ac': ['ignore']}

In [11]:
grounded_list[1]

{'sent': 'The sanctions against the school were a punishing blow, and they seemed to enforce the efforts the school had made to change.',
 'ans': 'enforce',
 'qc': ['blow',
  'change',
  'effort',
  'efforts',
  'sanction',
  'sanctions',
  'school',
  'seem',
  'seemed'],
 'ac': ['enforce']}

In [12]:
adj_path = '/home/minju/path_generator/commonsense-qa/data/csqa/graph/train.graph.adj.pk'

with open(adj_path, 'rb') as f:
    adj_mat = pickle.load(f)

In [15]:
adj_mat[0]

(<1224x72 sparse matrix of type '<class 'numpy.uint8'>'
 	with 345 stored elements in COOrdinate format>,
 array([  2373,   2846,   3078,   6008,  37504, 268859, 365229, 398047,
        666007,   2929,    295,    313,    579,   1360,   1363,   1415,
          1452,   1565,   1746,   2116,   2210,   2411,   2550,   2564,
          2843,   2916,   2979,   3082,   3199,   4629,   4695,   4762,
          5354,   5926,   6482,   6729,   7116,   7118,   7187,   7337,
          8139,   8380,   8789,   9366,   9699,  10015,  10287,  10336,
         10652,  11176,  11204,  11310,  11390,  13282,  13297,  15098,
         22675,  24516,  29231,  30264,  30298,  30442,  57265,  74303,
         74475,  87968,  89878, 107222, 135139, 147497, 346689, 403810],
       dtype=int32),
 array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        Fal

In [16]:
triple_path = '/home/minju/path_generator/commonsense-qa/data/csqa/triples/train.triples.pk'
with open(atriple_path 'rb') as f:
    triple = pickle.load(f)

In [18]:
triple[0][0]

(array([15, 15, 15,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  2,  5,  5,
         5,  5,  5,  5,  5,  5,  5,  5,  5,  7,  7,  7,  7,  7,  7,  7,  7,
         7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
         7,  7, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16,
        16, 16,  0,  0,  0,  0,  0,  0,  0,  1,  3,  5,  5,  5,  5,  5,  5,
         5,  5,  5,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
         7,  7,  7,  7,  7,  7,  7,  7, 10, 15, 15, 15, 15, 15, 15, 15, 15,
        15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        15, 

In [3]:
path_adj_path = '/home/minju/path_generator/commonsense-qa/data/csqa/paths/train.paths.adj.jsonl'
path_adj_list = []

with open(path_adj_path, 'r') as path_adj:
    for line in tqdm(path_adj):
        json_line = json.loads(line)
        path_adj_list.append(json_line)

48705it [04:03, 200.28it/s]


In [4]:
path_adj_list[0]

[{'ac': 2929,
  'qc': 2373,
  'pf_res': [{'path': [2373, 295, 6729, 2929], 'rel': [[15], [32], [15]]},
   {'path': [2373, 1360, 6729, 2929], 'rel': [[32], [32], [15]]},
   {'path': [2373, 295, 8789, 2929], 'rel': [[15], [32], [0]]},
   {'path': [2373, 1415, 6729, 2929], 'rel': [[15], [22], [15]]},
   {'path': [2373, 295, 10336, 2929], 'rel': [[15], [32], [0]]},
   {'path': [2373, 7116, 6729, 2929], 'rel': [[7, 15], [32], [15]]},
   {'path': [2373, 7118, 6729, 2929], 'rel': [[15], [32], [15]]},
   {'path': [2373, 11204, 6729, 2929], 'rel': [[15], [17, 32], [15]]},
   {'path': [2373, 7118, 10336, 2929], 'rel': [[15], [32], [0]]},
   {'path': [2373, 5354, 8789, 2929], 'rel': [[15], [32], [0]]},
   {'path': [2373, 10287, 8789, 2929], 'rel': [[15, 32], [7], [0]]},
   {'path': [2373, 5354, 10336, 2929], 'rel': [[15], [32], [0]]},
   {'path': [2373, 1452, 10336, 2929], 'rel': [[7], [24], [0]]},
   {'path': [2373, 5354, 15098, 2929], 'rel': [[15], [32], [0]]},
   {'path': [2373, 2210, 15098, 2

In [5]:
graph_adj_path = '/home/minju/path_generator/commonsense-qa/data/csqa/graph/train.graph.adj.pk'
with open(graph_adj_path 'rb') as f:
    graph_adj = pickle.load(f)

SyntaxError: invalid syntax (<ipython-input-5-c188e1583a8b>, line 2)