In [24]:
import pickle5 as pickle

path_embedding = '/home/minju/path_generator/commonsense-qa/path_embeddings/small_csqa/path_embedding.pickle'
with open(path_embedding, 'rb') as f:
    data = pickle.load(f)

In [2]:
len(data['train'])

9741

In [3]:
len(data['train'][0])

5

In [4]:
len(data['train'][0][0])

5

In [5]:
len(data['train'][0][0][0])

768

In [6]:
# 모르는 path 일때 이걸 뱉음
xxxxx = data['train'][9][1][4]

In [7]:
xxxxx

tensor([ 4.2628e-01, -4.2204e-01, -1.1409e+00,  4.9062e-01, -2.7811e-01,
         2.4344e-01, -2.1675e-01,  3.4046e-02,  3.0586e-01,  2.7978e-01,
        -1.6498e-01, -2.0800e-01, -2.1647e-02, -2.2455e-01, -4.0841e-01,
        -7.8654e-01, -6.4757e-02,  3.8431e-01,  2.5513e-01,  8.8241e-01,
         9.6752e-02,  4.7779e-01,  3.1301e-01, -5.7917e-01, -5.0270e-01,
         8.5986e-02, -6.7207e-02,  3.5982e-02,  3.0251e-01, -1.2977e-01,
        -1.8983e-01,  3.2059e-01, -4.7035e-01,  2.3685e-01,  1.2001e-01,
         2.8307e-01,  6.2461e+00, -2.0738e-01, -6.0874e-01,  1.1020e+00,
        -9.1592e-01,  1.6172e-01, -1.7159e-01, -5.2230e-01, -4.2962e-01,
         2.9666e-02, -4.4678e-01, -3.3752e-01,  7.3346e-01, -8.8767e-01,
         1.4220e-01,  1.2152e-01, -1.1976e+00, -2.3673e-01, -3.6939e-01,
         3.0887e-01, -4.6275e-01, -7.4750e-02, -1.5970e-02, -3.6371e-01,
        -1.4861e-02,  2.5144e-01,  8.7036e-02,  5.5058e-01, -1.0127e+00,
         1.6104e-01,  3.5418e-01, -4.6773e-01, -7.8

In [8]:
import json

inhouse_test_path = "/home/minju/path_generator/commonsense-qa/data/small_csqa/fairseq/inhouse/test.jsonl"

with open(inhouse_test_path, 'r') as fin:
        inhouse_test = [json.loads(line) for line in fin]

In [9]:
inhouse_test_id_list = []
for i in range(len(inhouse_test)):
    inhouse_test_id_list.append(inhouse_test[i]['id'])

In [10]:
len(inhouse_test_id_list)

100

In [11]:
train_path = '/home/minju/path_generator/commonsense-qa/data/small_csqa/train.jsonl'
with open(train_path, 'r') as fin:
        train = [json.loads(line) for line in fin]

In [12]:
train_index_list = []
for i in range(len(inhouse_test_id_list)):
    for j in range(len(train)):
        if inhouse_test_id_list[i] == train[j]['id']:
            train_index_list.append(j)

In [13]:
len(train_index_list)

100

In [14]:
train_index_list[0]

4

In [25]:
# generated_paths = '/home/minju/youngwookee/commonsense-qa/saved_models/generated_paths_all.txt'
# f = open(generated_paths, 'r')
# path_file = f.readlines()
# f.close()

In [26]:
# test_generated_paths = '/home/minju/youngwookee/commonsense-qa/saved_models/small_csqa/roberta-large_elr2e-6_dlr1e-3_d0.1_b16_s0/generated_inhouse_test_paths.txt'

# test_path_list = []

# f = open(test_generated_paths, 'a')
# for i in range(len(train_index_list)):
#     for j in range(len(path_file)):
#         if str(path_file[j].split(' ')[0]) == str(train_index_list[i]):
#             f.write(path_file[j])
#             test_path_list.append(path_file[j])
# f.close()

In [18]:
def delete_index(str):
    n1, n2, n3 = str.split(' ')
    n1 = int(n1)
    n2 = int(n2)
    n3 = int(n3)
    data['train'][n1][n2][n3] = xxxxx

In [32]:
def input_index(str):
    n1, n2, n3 = str.split(' ')
    n1 = int(n1)
    n2 = int(n2)
    n3 = int(n3)
    new_data['train'][n1][n2][n3] = data['train'][n1][n2][n3]

In [35]:
wrong_paths = '/home/minju/path_generator/commonsense-qa/data/small_csqa/wrong_path_index.txt'
f = open(wrong_paths, 'r')
wrong_path_list = f.readlines()
f.close()

In [21]:
train_index_list[:10]

[4, 6, 25, 33, 46, 52, 62, 74, 91, 92]

In [25]:
## only wrong index
import copy

new_data = copy.deepcopy(data)

for i in range(len(train_index_list)):
    for j in range(len(new_data['train'][0])):
        for k in range(len(new_data['train'][0][0])):
            new_data['train'][i][j][k] = xxxxx

In [37]:
for i in range(len(wrong_path_list)):
    input_index(wrong_path_list[i])
    

In [20]:
len(wrong_path_list)

166

In [6]:
for i in range(len(wrong_path_list)):
    delete_index(wrong_path_list[i])

    True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, 

ValueError: too many values to unpack (expected 3)

In [8]:
wrong_path_list[23]

'46 0 0\n'

In [38]:
save_file = "/home/minju/path_generator/commonsense-qa/path_embeddings/small_csqa/path_embedding_minju.pickle"
with open(save_file, 'wb') as handle:
        pickle.dump(new_data, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [34]:
path_embedding = "/home/minju/youngwookee/commonsense-qa/path_embeddings/small_csqa/path_embedding_minju.pickle"
with open(path_embedding, 'rb') as f:
    data = pickle.load(f)

In [35]:
wrong_path_list[13]

'6 2 2\n'

In [9]:
data['train'][46][0][0]

tensor([ 4.2628e-01, -4.2204e-01, -1.1409e+00,  4.9062e-01, -2.7811e-01,
         2.4344e-01, -2.1675e-01,  3.4046e-02,  3.0586e-01,  2.7978e-01,
        -1.6498e-01, -2.0800e-01, -2.1647e-02, -2.2455e-01, -4.0841e-01,
        -7.8654e-01, -6.4757e-02,  3.8431e-01,  2.5513e-01,  8.8241e-01,
         9.6752e-02,  4.7779e-01,  3.1301e-01, -5.7917e-01, -5.0270e-01,
         8.5986e-02, -6.7207e-02,  3.5982e-02,  3.0251e-01, -1.2977e-01,
        -1.8983e-01,  3.2059e-01, -4.7035e-01,  2.3685e-01,  1.2001e-01,
         2.8307e-01,  6.2461e+00, -2.0738e-01, -6.0874e-01,  1.1020e+00,
        -9.1592e-01,  1.6172e-01, -1.7159e-01, -5.2230e-01, -4.2962e-01,
         2.9666e-02, -4.4678e-01, -3.3752e-01,  7.3346e-01, -8.8767e-01,
         1.4220e-01,  1.2152e-01, -1.1976e+00, -2.3673e-01, -3.6939e-01,
         3.0887e-01, -4.6275e-01, -7.4750e-02, -1.5970e-02, -3.6371e-01,
        -1.4861e-02,  2.5144e-01,  8.7036e-02,  5.5058e-01, -1.0127e+00,
         1.6104e-01,  3.5418e-01, -4.6773e-01, -7.8

In [11]:
xxxxx.size()

torch.Size([768])

In [13]:
import torch
zero_vector = torch.zeros(768)

In [14]:
for i in range(len(data['train'])):
    for j in range(len(data['train'][0])):
        for k in range(len(data['train'][0][0])):
            data['train'][i][j] = zero_vector

In [15]:
data['train'][0][1]

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [36]:
data['train'][5][1]

tensor([[ 0.4263, -0.4220, -1.1409,  ...,  0.2609,  0.2070, -0.2158],
        [ 0.4263, -0.4220, -1.1409,  ...,  0.2609,  0.2070, -0.2158],
        [ 0.4263, -0.4220, -1.1409,  ...,  0.2609,  0.2070, -0.2158],
        [ 0.4263, -0.4220, -1.1409,  ...,  0.2609,  0.2070, -0.2158],
        [ 0.4263, -0.4220, -1.1409,  ...,  0.2609,  0.2070, -0.2158]])

In [16]:
save_file = "/home/minju/path_generator/commonsense-qa/path_embeddings/small_csqa/path_embedding_minju.pickle"
with open(save_file, 'wb') as handle:
        pickle.dump(data, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [38]:
import pickle5 as pickle

path_embedding = '/home/minju/path_generator/commonsense-qa/path_embeddings/small_csqa/path_embedding_minju.pickle'
with open(path_embedding, 'rb') as f:
    data = pickle.load(f)

In [40]:
data['train'][10][1]

tensor([[ 0.4263, -0.4220, -1.1409,  ...,  0.2609,  0.2070, -0.2158],
        [ 0.4263, -0.4220, -1.1409,  ...,  0.2609,  0.2070, -0.2158],
        [ 0.4263, -0.4220, -1.1409,  ...,  0.2609,  0.2070, -0.2158],
        [ 0.4263, -0.4220, -1.1409,  ...,  0.2609,  0.2070, -0.2158],
        [ 0.4263, -0.4220, -1.1409,  ...,  0.2609,  0.2070, -0.2158]])